extern crate cc;

fn main() {
    cc::Build::new()
        .no_default_flags(true)
        .compiler("riscv64-unknown-elf-xuantie-gcc")
        .include("src/bare")
        .file("src/bare/clint.c")
        .file("src/bare/clk.c")
        .file("src/bare/common.c")
        .file("src/bare/gpio.c")
        .file("src/bare/interrupt.c")
        .file("src/bare/main.c")
        .file("src/bare/printf.c")
        .file("src/bare/start.S")
        .file("src/bare/timer.c")
        .file("src/bare/trap.S")
        .file("src/bare/uart.c")
        // .file("src/kernel/portASM.S")
        // .flag("-Wall")
        .flag("-O2")
        .flag("-fno-omit-frame-pointer")
        .flag("-ggdb")
        .flag("-march=rv64gcvxtheadc")
        .flag("-mabi=lp64d")
        .flag("-mtune=c906")
        .flag("-MD")
        .flag("-mcmodel=medany")
        .flag("-ffreestanding")
        .flag("-fno-common")
        .flag("-nostdlib")
        .flag("-mno-relax")
        .flag("-fno-stack-protector")
        .flag("-fno-pie")
        .flag("-no-pie")
        .compile("bare");
}
