[package]
name = "r_freertos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.5.2"
buddy_system_allocator = "0.8.0"

[build-dependencies]
cc = "1.0"

