name: Rust

on:
  push:
    branches: [main,dev,dev-doc]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Build doc
        run: cargo doc --no-deps --verbose
      - name: Generate index.html
        run: echo '<meta http-equiv=refresh content=0;url=target/riscv32imac-unknown-none-elf/doc/r_freertos/index.html>' > ./doc/index.html
      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc